name: indigi_attendance
description: "Indigi Attendance is a mobile application for managing employee attendance."
publish_to: 'none'
version: 1.1.1+4

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  provider: ^6.1.5+1
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  geolocator: ^9.0.2
  geocoding: ^4.0.0
  shared_preferences: ^2.2.2
  fl_chart: ^1.1.1  
  url_launcher: ^6.3.2
  flutter_secure_storage: ^9.0.0
  uuid: ^4.3.3
  device_info_plus: ^10.1.0
  cached_network_image: ^3.4.1
  upgrader: ^12.3.0
  package_info_plus: ^8.0.0
  google_maps_flutter: ^2.14.0
  file_picker: ^10.3.8
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/app_icon.png